export const estadosECidades = {
  "Acre": ["Rio Branco", "Cruzeiro do Sul", "Sena Madureira"],
  "Alagoas": ["Maceió", "Arapiraca", "Palmeira dos Índios"],
  "Amapá": ["Macapá", "Santana", "Oiapoque"],
  "Amazonas": ["Manaus", "Parintins", "Itacoatiara"],
  "Bahia": ["Salvador", "Feira de Santana", "Vitória da Conquista"],
  "Ceará": ["Fortaleza", "Juazeiro do Norte", "Sobral"],
  "Distrito Federal": ["Brasília"],
  "Espírito Santo": ["Vitória", "Vila Velha", "Serra"],
  "Goiás": ["Goiânia", "Anápolis", "Aparecida de Goiânia"],
  "Maranhão": ["São Luís", "Imperatriz", "Timon"],
  "Mato Grosso": ["Cuiabá", "Várzea Grande", "Rondonópolis"],
  "Mato Grosso do Sul": ["Campo Grande", "Dourados", "Três Lagoas"],
  "Minas Gerais": ["Belo Horizonte", "Uberlândia", "Contagem"],
  "Pará": ["Belém", "Ananindeua", "Santarém"],
  "Paraíba": ["João Pessoa", "Campina Grande", "Patos"],
  "Paraná": ["Curitiba", "Londrina", "Maringá"],
  "Pernambuco": ["Recife", "Olinda", "Caruaru"],
  "Piauí": ["Teresina", "Parnaíba", "Picos"],
  "Rio de Janeiro": ["Rio de Janeiro", "Niterói", "Petrópolis"],
  "Rio Grande do Norte": ["Natal", "Mossoró", "Parnamirim"],
  "Rio Grande do Sul": ["Porto Alegre", "Caxias do Sul", "Pelotas"],
  "Rondônia": ["Porto Velho", "Ji-Paraná", "Ariquemes"],
  "Roraima": ["Boa Vista", "Rorainópolis", "Caracaraí"],
  "Santa Catarina": ["Florianópolis", "Joinville", "Blumenau"],
  "São Paulo": ["São Paulo", "Campinas", "Santos"],
  "Sergipe": ["Aracaju", "Nossa Senhora do Socorro", "Lagarto"],
  "Tocantins": ["Palmas", "Araguaína", "Gurupi"],
};
